on:
  push:
    branches:    
      - '*'
    tags:
      - 'v*'
  pull_request:
    branches:    
      - main



name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings


  release:
    name: Release crate
    runs-on: ubuntu-latest
    needs: [check, test, clippy, fmt]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Release jupiter_common to crates.io
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          command: publish 
          args: -p jupiter_common --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Fetch
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          command: fetch 
      - name: Release stt to crates.io
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          command: publish 
          args: -p stt --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Fetch
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          command: fetch 
      - name: Release jupiter_downloader to crates.io
        uses: actions-rs/cargo@v1
        #if: startsWith(github.ref, 'refs/tags/v')
        with:
          command: publish 
          args: -p jupiter_downloader --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Fetch
        uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          command: fetch 
      - name: Release podcast2text to crates.io
        uses: actions-rs/cargo@v1
        #if: startsWith(github.ref, 'refs/tags/v')
        with:
          command: publish 
          args: -p podcast2text --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
