on:
  push:
    branches:    
      - 'main'
    tags:
      - 'v*'

name: Build and release docker images



env:
  DOCKER_BUILDKIT: 1 

jobs:

  docker_build:

    name: Release docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: flakm/downloader:latest

      - name: Build and push
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: flakm/downloader:${{ github.ref }}
